package com.smsg.ui.screens
import androidx.compose.foundation.clickable; import androidx.compose.foundation.layout.*; import androidx.compose.foundation.lazy.LazyColumn; import androidx.compose.foundation.lazy.items; import androidx.compose.foundation.shape.CircleShape; import androidx.compose.material.icons.Icons; import androidx.compose.material.icons.filled.Archive; import androidx.compose.material.icons.filled.Search; import androidx.compose.material3.*; import androidx.compose.runtime.*; import androidx.compose.ui.Alignment; import androidx.compose.ui.Modifier; import androidx.compose.ui.draw.clip; import androidx.compose.ui.platform.LocalContext; import androidx.compose.ui.text.font.FontWeight; import androidx.compose.ui.unit.dp; import com.google.accompanist.permissions.ExperimentalPermissionsApi; import com.google.accompanist.permissions.rememberMultiplePermissionsState; import com.smsg.data.model.Conversation; import com.smsg.data.repository.SmsRepository; import java.text.SimpleDateFormat
@OptIn(ExperimentalPermissionsApi::class, ExperimentalMaterial3Api::class)
@Composable
fun ConversationListScreen(onConversationClick: (Long, String) -> Unit) {
    val ctx = LocalContext.current; val repo = remember { SmsRepository(ctx) }; var convs by remember { mutableStateOf<List<Conversation>>(emptyList()) }; var q by remember { mutableStateOf("") }
    val perms = rememberMultiplePermissionsState(listOf(android.Manifest.permission.READ_SMS, android.Manifest.permission.SEND_SMS, android.Manifest.permission.READ_CONTACTS))
    LaunchedEffect(perms.allPermissionsGranted) { if (perms.allPermissionsGranted) convs = repo.getConversations() }; LaunchedEffect(Unit) { perms.launchMultiplePermissionRequest() }
    Scaffold(topBar = { TopAppBar(title = { Text("Messages", fontWeight = FontWeight.Medium) }, actions = { IconButton(onClick = {}) { Icon(Icons.Default.Archive, null) } }) }, floatingActionButton = { ExtendedFloatingActionButton(onClick = {}, text = { Text("Nouveau message") }) }) { pad ->
        Column(Modifier.padding(pad).fillMaxSize()) {
            OutlinedTextField(value = q, onValueChange = { q = it }, modifier = Modifier.fillMaxWidth().padding(16.dp), placeholder = { Text("Rechercher dans les messages") }, leadingIcon = { Icon(Icons.Default.Search, null) }, shape = MaterialTheme.shapes.extraLarge, singleLine = true)
            if (!perms.allPermissionsGranted) { Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) { Button(onClick = { perms.launchMultiplePermissionRequest() }) { Text("Autoriser les SMS") } } }
            else { LazyColumn { items(convs.filter { it.address.contains(q, true) || it.snippet.contains(q, true) }) { c -> Row(Modifier.fillMaxWidth().clickable { onConversationClick(c.id, c.address) }.padding(16.dp), verticalAlignment = Alignment.CenterVertically) { Surface(Modifier.size(40.dp).clip(CircleShape), color = MaterialTheme.colorScheme.primaryContainer) { Box(contentAlignment = Alignment.Center) { Text((c.contactName?.firstOrNull()?: c.address.firstOrNull()?: "?").toString().uppercase()) } }; Spacer(Modifier.width(16.dp)); Column(Modifier.weight(1f)) { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) { Text(c.contactName?: c.address, fontWeight = FontWeight.Medium); Text(SimpleDateFormat("HH:mm", java.util.Locale.FRANCE).format(java.util.Date(c.date)), style = MaterialTheme.typography.labelSmall) }; Text(c.snippet, maxLines = 1) } } } } }
        }
    }
}
